# Generated by Django 4.2.3 on 2023-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_alter_cart_user'),
        ('product', '0006_alter_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='products', to='cart.cart'),
        ),
    ]
