# Generated by Django 4.2.3 on 2023-07-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_cart_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
