# Generated by Django 4.2.3 on 2023-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_cart'),
        ('cart', '0002_remove_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='products', to='product.product'),
        ),
    ]
